version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      time: "00:00"
      interval: daily
    ignore:
      - dependency-name: "laravel/framework"
        update-types: ["version-update:semver-major"]
      - dependency-name: "laravel/sanctum"
        update-types: ["version-update:semver-major"]
