### Generate user token
POST {{$dotenv APP_URL}}api/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "token_name": "Mobile Phone Token",
    "email": "{{$dotenv USER_EMAIL}}",
    "password": "{{$dotenv USER_PASSWORD}}",
    "expired_at": "2022-05-21"
}

### Revoke current user token
POST {{$dotenv APP_URL}}api/logout HTTP/1.1
Accept: application/json
Authorization: Bearer {{$dotenv PERSONAL_ACCESS_TOKEN}}
Content-Type: application/json
