### Get all books
GET {{$dotenv APP_URL}}api/books HTTP/1.1
Accept: application/json
Authorization: Bearer {{$dotenv PERSONAL_ACCESS_TOKEN}}
Content-Type: application/json

### Show a book
GET {{$dotenv APP_URL}}api/books/1984 HTTP/1.1
Accept: application/json
Authorization: Bearer {{$dotenv PERSONAL_ACCESS_TOKEN}}
Content-Type: application/json

### Search books by keyword
GET {{$dotenv APP_URL}}api/books/search?keyword=1984 HTTP/1.1
Accept: application/json
Authorization: Bearer {{$dotenv PERSONAL_ACCESS_TOKEN}}
Content-Type: application/json
